# Generated by Django 5.0 on 2024-03-14 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=300)),
                ('line2', models.CharField(max_length=300)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('created_by', models.IntegerField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileno', models.BigIntegerField()),
                ('emailid', models.CharField(max_length=200)),
                ('accountno', models.BigIntegerField()),
                ('beneficaryname', models.CharField(max_length=300)),
                ('created_by', models.IntegerField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=300)),
                ('vendorcode', models.CharField(max_length=200)),
                ('vendorgst', models.CharField(max_length=300)),
                ('vendorpan', models.CharField(max_length=300)),
                ('vendorbranch', models.CharField(max_length=300)),
                ('created_by', models.IntegerField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('vendoraddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_details.address_details')),
                ('vendorcontact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_details.contact_details')),
            ],
        ),
    ]
