# Generated by Django 5.0 on 2024-03-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_address_details_contact_details_vendor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_details',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='created_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor_details',
            name='created_by',
            field=models.IntegerField(),
        ),
    ]
