# Generated by Django 5.0 on 2024-04-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_alter_address_details_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registermodel',
        ),
    ]
