# Generated by Django 5.0 on 2024-04-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_registermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registermodel',
        ),
    ]
